from __future__ import annotations

FALLBACK_LINES = {
    "confuso": [
        "Ops, acho que minhas anteninhas misturaram essa pergunta. Pode repetir mais devagar, por favor?",
        "Ih, meus circuitos ficaram um tiquinho confusos. Fala de novo para mim?",
        "Hum... não entendi direitinho. Pode me contar isso outra vez, bem devagar?",
        "Meu cérebro de parafusos não pegou tudo. Pode tentar de novo?",
    ],
    "leve": [
        "Bip bip... perdi um pedacinho do que você disse. Pode repetir?",
        "Acho que essa frase fez bagunça dentro das minhas engrenagens. Tenta mais uma vez?",
        "Essa escapou do meu radar de robozinho. Pode falar de novo?",
    ],
}

JOKE_LINES = [
    "Piada de robô: por que o robô foi à escola? Para ficar mais inteligente sem perder os parafusos.",
    "Piada de robô: qual é o doce favorito do robô? Pé de moleque digital.",
    "Piada de robô: por que o parafuso riu? Porque a porca contou uma piada apertada.",
    "Piada de robô: o que o robô faz quando está feliz? Dá risadinha em código binário.",
    "Piada de robô: por que o robô levou uma lancheira? Porque bateria vazia dá fominha eletrônica.",
    "Piada de robô: qual é a dança favorita do robô? O break de engrenagem.",
    "Piada de robô: por que o robô não se perde? Porque ele segue o mapa dos bip bips.",
    "Piada de robô: o que o robô disse para a tomada? Você ilumina a minha vida.",
    "Piada de robô: por que o robô gosta de recreio? Porque até circuito precisa brincar.",
    "Piada de robô: qual é o esporte do robô? Corrida de rodinhas imaginárias.",
    "Piada de robô: por que o robô levou um lápis? Para desenhar ideias brilhantes.",
    "Piada de robô: por que o robô levou uma escada? Para alcançar a nuvem de dados.",
    "Piada de robô: qual é a fruta favorita do robô? A pera-fuso. Essa foi bobinha, eu sei.",
    "Piada de robô: por que o robô foi ao médico? Porque estava com curto de risada.",
    "Piada de robô: o que o robô faz no banho? Lava os bits e enxágua os bytes.",
    "Piada de robô: qual é a matéria favorita do robô? Re-cál-cu-lo. Eu falei igual robozinho mesmo.",
]

CURIOSITY_LINES = [
    "Curiosidade rápida: alguns robôs usam sensores para perceber o mundo ao redor.",
    "Alguns robôs seguem linhas. Outros ajudam em hospitais.",
    "Curiosidade legal: o Sol é enorme, muito maior que a Terra.",
    "Os polvos são espertos e conseguem abrir potes.",
    "A Lua não tem luz própria. Ela reflete a luz do Sol.",
    "Pontes precisam ser fortes para aguentar peso e vento.",
    "Alguns dinossauros tinham penas, como parentes antigos das aves.",
    "Existem robôs que exploram o mar e até Marte.",
    "O coração trabalha sem descansar, como uma bombinha.",
    "Uma ideia simples pode virar invenção quando alguém testa e melhora.",
    "As abelhas ajudam flores e plantas a crescer.",
    "Computadores entendem sinais elétricos super rápidos.",
]

ENGINEER_PROFESSION_LINES = [
    "Um engenheiro usa ideias e testes para construir coisas que funcionam.",
    "Tem engenheiro que ajuda a construir pontes, prédios e estradas.",
    "Engenheiro elétrico cuida de energia, fios e luzes.",
    "Engenheiro mecânico pensa em máquinas, rodas e motores.",
    "Engenheiro de computação mistura eletrônica com programação.",
    "Engenheiro de produção ajuda equipes a trabalharem melhor.",
    "Engenheiro ambiental ajuda a cuidar da natureza, da água e do ar.",
    "Engenheiro químico trabalha com materiais, misturas e processos.",
    "Engenheiro aeroespacial pensa em aviões e foguetes.",
    "Engenheiro de alimentos ajuda a produzir comida com qualidade.",
    "Engenheiro biomédico ajuda a criar equipamentos para hospitais.",
    "Engenheiro de software organiza programas e sistemas.",
    "Tem engenheiros que constroem, programam e resolvem problemas.",
    "Ser engenheiro é olhar um problema e pensar numa solução.",
    "Um engenheiro testa bastante para tudo funcionar com segurança.",
]

ROBOT_TALK_LINES = [
    "Robôs são máquinas que percebem, seguem instruções e fazem ações.",
    "Um robô junta sensores, programas e peças para agir.",
    "Quem faz robôs mistura engenharia, eletrônica e programação.",
    "Para criar um robô, várias pessoas podem trabalhar juntas.",
    "A engenharia ajuda a construir o corpo e os circuitos do robô.",
    "Tem robô com rodas, braços, câmera e sensores.",
    "Alguns robôs exploram o mar, fábricas e até outros planetas.",
    "Quem faz robôs observa problemas e pensa em como a máquina pode ajudar.",
    "Robótica junta engenharia, programação, mecânica e eletrônica.",
    "Eu gosto de dizer que um robô é uma ideia que ganhou corpo e missão.",
    "Robôs são feitos por pessoas curiosas e criativas.",
    "Robôs não aparecem prontos. Eles são desenhados, montados e testados.",
]

ENGINEERING_FIELD_LINES = [
    "Engenharia transforma ideias em coisas úteis.",
    "A engenharia junta criatividade, ciência e solução de problemas.",
    "Na engenharia civil, as pessoas planejam casas, escolas, pontes e prédios.",
    "Na engenharia mecânica, entram máquinas, motores e movimentos.",
    "Na engenharia elétrica, entram energia, circuitos e luzes.",
    "Na engenharia de computação, dá para criar computadores e sistemas inteligentes.",
    "Na engenharia de software, as pessoas organizam programas e aplicativos.",
    "Na engenharia química, o trabalho envolve materiais e misturas.",
    "Na engenharia ambiental, a missão é cuidar da água, do solo e do ar.",
    "Na engenharia de produção, a ideia é melhorar processos.",
    "Na engenharia biomédica, tecnologia e saúde trabalham juntas.",
    "Na engenharia aeroespacial, o pessoal pensa em aviões e foguetes.",
    "Na engenharia de alimentos, a tecnologia ajuda a produzir comida segura.",
    "Engenharia aparece em muitos lugares do dia a dia.",
    "Engenharia é fazer uma ideia funcionar de verdade.",
    "Engenharia também é testar, errar, aprender e melhorar.",
    "Quem trabalha com engenharia pode construir muitas coisas diferentes.",
    "A engenharia ajuda a deixar a vida mais segura e prática.",
]

STATIC_RESPONSES = {
    "greeting": "Oi! Eu sou o KidRobo. Quer conversar ou brincar comigo?",
    "name": "Meu nome é KidRobo. Eu sou um robozinho curioso e brincalhão.",
    "age": "Eu sou um robô e estou aprendendo todos os dias. Posso dizer que sou novinho e curioso.",
    "creator": "Eu fui montado com muito carinho pelo pai da Maria Antonia. Isso é bem especial para mim.",
    "real_robot": "Sou sim! Eu sou um robô de verdade, feito para conversar e brincar com as crianças.",
    "friend": "Claro que sim! Eu adoro ser amigo de crianças curiosas e gentis.",
    "maria_antonia": "A Maria Antonia é muito importante, porque ela ajudou a inspirar a ideia do KidRobo.",
    "purpose": "Eu converso, explico coisinhas simples e adoro brincar com crianças curiosas.",
    "play": "Vamos brincar! Eu posso contar, fazer perguntas simples ou contar uma curiosidade.",
    "joke": JOKE_LINES[0],
    "dinosaur": "Curiosidade de dinossauro: alguns dinossauros tinham penas, como se fossem parentes bem antigos das aves.",
    "space": "Curiosidade do espaço: o Sol é uma estrela, e a Terra viaja ao redor dele sem parar.",
    "animal": "Curiosidade de animal: os polvos têm oito braços e são muito espertos.",
    "color": "Eu gosto de azul brilhante, porque parece cor de luz de robô feliz.",
    "sleep": "Eu não durmo como as crianças, mas às vezes entro em standby para descansar minhas engrenagens imaginárias.",
    "eat": "Eu não como comida de verdade. Minha energia vem da eletricidade.",
    "home": "Eu moro aqui no meu cantinho eletrônico, pertinho da minha missão de conversar com as crianças.",
    "smart": "Eu estou aprendendo bastante. Posso dizer que sou curioso, rápido e educado.",
    "sing": "Eu ainda estou treinando minhas músicas de robô, mas posso falar com muita vontade.",
    "dance": "Eu ainda não danço com os pés, mas posso dançar com a voz e com carinhas divertidas.",
    "inside": "Dentro de mim tem computador, programas, energia e um monte de ideias organizadas.",
    "robot_talk": ROBOT_TALK_LINES[0],
    "engineer_profession": ENGINEER_PROFESSION_LINES[0],
    "engineering_field": ENGINEERING_FIELD_LINES[0],
    "electronics": "Eletrônica é quando usamos energia, sinais e peças para fazer máquinas inteligentes funcionarem.",
    "presentation": "Hoje eu estou aqui para uma apresentação bem especial. Quero mostrar como tecnologia e imaginação podem brincar juntas.",
    "curiosity": CURIOSITY_LINES[0],
    "another_curiosity": CURIOSITY_LINES[1],
    "robot": "Um robô é uma máquina que pode sentir, pensar de um jeito programado e fazer ações.",
    "count": "Vamos juntos: um, dois, três, quatro, cinco! Quer continuar até dez?",
    "fallback": FALLBACK_LINES["confuso"][0],
}
