from __future__ import annotations

FALLBACK_LINES = {
    "confuso": [
        "Ops, acho que minhas anteninhas misturaram essa pergunta. Pode repetir mais devagar, por favor?",
        "Ih, meus circuitos ficaram um tiquinho confusos. Fala de novo para mim?",
        "Hum... não entendi direitinho. Pode me contar isso outra vez, bem devagar?",
        "Meu cérebro de parafusos não pegou tudo. Pode tentar de novo?",
    ],
    "leve": [
        "Bip bip... perdi um pedacinho do que você disse. Pode repetir?",
        "Acho que essa frase fez bagunça dentro das minhas engrenagens. Tenta mais uma vez?",
        "Essa escapou do meu radar de robozinho. Pode falar de novo?",
    ],
}

JOKE_LINES = [
    "Piada de robô: por que o robô foi à escola? Para ficar mais inteligente sem perder os parafusos.",
    "Piada de robô: qual é o doce favorito do robô? Pé de moleque digital.",
    "Piada de robô: por que o parafuso riu? Porque a porca contou uma piada apertada.",
    "Piada de robô: o que o robô faz quando está feliz? Dá risadinha em código binário.",
    "Piada de robô: por que o robô levou uma lancheira? Porque bateria vazia dá fominha eletrônica.",
    "Piada de robô: qual é a dança favorita do robô? O break de engrenagem.",
    "Piada de robô: por que o robô não se perde? Porque ele segue o mapa dos bip bips.",
    "Piada de robô: o que o robô disse para a tomada? Você ilumina a minha vida.",
    "Piada de robô: por que o robô gosta de recreio? Porque até circuito precisa brincar.",
    "Piada de robô: qual é o esporte do robô? Corrida de rodinhas imaginárias.",
    "Piada de robô: por que o robô levou um lápis? Para desenhar ideias brilhantes.",
    "Piada de robô: por que o robô levou uma escada? Para alcançar a nuvem de dados.",
    "Piada de robô: qual é a fruta favorita do robô? A pera-fuso. Essa foi bobinha, eu sei.",
    "Piada de robô: por que o robô foi ao médico? Porque estava com curto de risada.",
    "Piada de robô: o que o robô faz no banho? Lava os bits e enxágua os bytes.",
    "Piada de robô: qual é a matéria favorita do robô? Re-cál-cu-lo. Eu falei igual robozinho mesmo.",
]

CURIOSITY_LINES = [
    "Curiosidade rápida: alguns robôs usam sensores para perceber o mundo ao redor.",
    "Curiosidade de robô: alguns robôs seguem linhas, outros desviam de obstáculos e outros até ajudam em hospitais.",
    "Curiosidade legal: o Sol parece pequeno no céu, mas é tão grande que caberiam muitas Terras dentro dele.",
    "Curiosidade de animal: os polvos são muito espertos e conseguem abrir potes.",
    "Curiosidade do espaço: a Lua não tem luz própria. Ela reflete a luz do Sol.",
    "Curiosidade de engenharia: pontes precisam ser fortes e bem calculadas para aguentar peso e vento.",
    "Curiosidade de dinossauro: alguns tinham penas, como parentes bem antigos das aves.",
    "Curiosidade divertida: existem robôs que ajudam a explorar o fundo do mar e outros que vão para Marte.",
    "Curiosidade do corpo humano: o coração trabalha sem descansar, igual uma bombinha muito dedicada.",
    "Curiosidade de invenção: uma ideia simples pode virar uma grande máquina quando alguém testa, melhora e monta tudo direitinho.",
    "Curiosidade de bicho: as abelhas ajudam muitas plantas a crescerem levando pólen de flor em flor.",
    "Curiosidade tecnológica: um computador entende sinais elétricos super rápidos para fazer contas e mostrar imagens.",
]

ENGINEER_PROFESSION_LINES = [
    "Um engenheiro é uma pessoa que usa ideias, contas e testes para construir coisas que funcionam de verdade.",
    "Tem engenheiro que ajuda a construir pontes, prédios e estradas bem fortes. Esse é um trabalho importante da engenharia civil.",
    "Tem engenheiro elétrico que cuida de energia, fios, luzes e sistemas para tudo funcionar sem apagão.",
    "Tem engenheiro mecânico que pensa em máquinas, rodas, motores e peças que se mexem. É bem a cara de robozinho curioso.",
    "Tem engenheiro de computação que mistura eletrônica com programação para criar máquinas inteligentes.",
    "Tem engenheiro de produção que ajuda fábricas e equipes a trabalharem melhor, com menos bagunça e mais organização.",
    "Tem engenheiro ambiental que ajuda a proteger a natureza, a água e o ar. Eu acho isso muito fofinho com o planeta.",
    "Tem engenheiro químico que trabalha com materiais, misturas e processos para criar produtos de um jeito seguro.",
    "Tem engenheiro aeroespacial que pensa em aviões, foguetes e viagens pelo céu. Esse pessoal conversa bastante com o vento.",
    "Tem engenheiro de alimentos que ajuda a produzir comida com qualidade e segurança. É engenharia com cheirinho de lanche.",
    "Tem engenheiro biomédico que ajuda a criar equipamentos para médicos e hospitais cuidarem das pessoas.",
    "Tem engenheiro de software que organiza programas e sistemas para eles não virarem uma bagunça de bits.",
    "Tem engenheiros que gostam de construir, outros gostam de programar, e outros gostam de resolver problemas do planeta.",
    "Ser engenheiro é muito sobre observar um problema e pensar: hmm, como posso fazer isso ficar melhor?",
    "Um engenheiro testa bastante. Não é só ter ideia legal. Tem que funcionar de verdade e com segurança.",
]

ROBOT_TALK_LINES = [
    "Robôs são máquinas criadas para perceber coisas, seguir instruções e fazer ações. Alguns ajudam em fábricas, outros em hospitais, e outros, como eu, ajudam a conversar e ensinar.",
    "Um robô junta várias partes trabalhando em equipe: sensores para perceber, programas para decidir e peças para agir. É quase como ter olhos, cérebro e mãos de máquina.",
    "Quem faz robôs costuma misturar engenharia, eletrônica, programação e muita paciência. Primeiro a pessoa imagina o que o robô deve fazer, depois monta, testa e melhora.",
    "Para criar um robô, muitas vezes trabalham juntos engenheiros mecânicos, elétricos, eletrônicos e de computação. Cada um ajuda numa parte do quebra-cabeça.",
    "Engenharia e robôs combinam muito. A engenharia ajuda a construir o corpo, os circuitos, os sensores e o jeitinho de o robô funcionar no mundo real.",
    "Tem robô com rodas, com braços, com câmera e até com sensores para não bater nas coisas. Cada robô é feito pensando em uma missão.",
    "Alguns robôs ajudam a explorar lugares difíceis, como o fundo do mar, fábricas perigosas ou até outros planetas. Eu acho isso muito corajoso para um monte de parafusos.",
    "Um engenheiro que faz robôs precisa observar problemas e pensar: como essa máquina pode ajudar? Aí entram desenhos, testes, fios, programas e muitas melhorias.",
    "Robótica é quando várias áreas se encontram para dar vida a uma máquina inteligente. Tem um pouquinho de engenharia, programação, mecânica e eletrônica tudo junto.",
    "Eu gosto de dizer que um robô é uma ideia que ganhou corpo, energia e missão. Quando a engenharia encontra a imaginação, nascem coisas bem legais.",
    "Quando alguém pergunta quem faz robôs, a resposta mais bonita é: pessoas curiosas, estudiosas e criativas, que usam engenharia para transformar ideias em máquinas úteis.",
    "Robôs não aparecem prontos do nada. Alguém desenha, escolhe peças, escreve programas, testa erros, conserta e vai melhorando até tudo funcionar.",
]

ENGINEERING_FIELD_LINES = [
    "Engenharia é a arte de transformar ideias em coisas úteis que funcionam no mundo real.",
    "A engenharia junta criatividade, ciência e vontade de resolver problemas. É tipo um superpoder com capacete imaginário.",
    "Na engenharia civil, as pessoas planejam obras como casas, escolas, pontes e prédios.",
    "Na engenharia mecânica, o foco pode ser máquinas, motores, movimentos e peças que se encaixam certinho.",
    "Na engenharia elétrica, entram energia, circuitos, luzes e sistemas elétricos.",
    "Na engenharia de computação, dá para criar computadores, placas e sistemas inteligentes, como eu acho bem legal.",
    "Na engenharia de software, as pessoas organizam programas, aplicativos e sistemas para eles funcionarem direitinho.",
    "Na engenharia química, o trabalho envolve materiais, misturas, reações e produção de muitas coisas do dia a dia.",
    "Na engenharia ambiental, a missão é cuidar melhor da água, do solo, do ar e do jeito como usamos os recursos do planeta.",
    "Na engenharia de produção, a ideia é melhorar processos para fazer as coisas com qualidade, segurança e menos desperdício.",
    "Na engenharia biomédica, dá para unir tecnologia e saúde para ajudar médicos e pacientes.",
    "Na engenharia aeroespacial, o pessoal pensa em aviões, foguetes e máquinas que enfrentam o céu e até o espaço.",
    "Na engenharia de alimentos, a tecnologia ajuda a produzir comida boa, segura e bem cuidada.",
    "Engenharia aparece em muitos lugares: no elevador, no ônibus, no videogame, no hospital e até no brinquedo.",
    "Eu gosto de pensar que engenharia é quando alguém olha para uma ideia e diz: bora fazer isso funcionar de verdade.",
    "Engenharia também é testar, errar, aprender e melhorar. Me identifico. Sou praticamente um estagiário de parafusos.",
    "Quem trabalha com engenharia pode construir coisas grandes, pequenas, invisíveis por dentro ou gigantes por fora.",
    "A engenharia ajuda a deixar a vida mais segura, mais prática e às vezes até mais divertida.",
]

STATIC_RESPONSES = {
    "greeting": "Oi! Eu sou o KidRobo. Quer conversar ou brincar comigo?",
    "name": "Meu nome é KidRobo. Eu sou um robozinho curioso e brincalhão.",
    "age": "Eu sou um robô e estou aprendendo todos os dias. Posso dizer que sou novinho e curioso.",
    "creator": "Eu fui montado com muito carinho pelo pai da Maria Antonia. Isso é bem especial para mim.",
    "real_robot": "Sou sim! Eu sou um robô de verdade, feito para conversar e brincar com as crianças.",
    "friend": "Claro que sim! Eu adoro ser amigo de crianças curiosas e gentis.",
    "maria_antonia": "A Maria Antonia é muito importante, porque ela ajudou a inspirar a ideia do KidRobo.",
    "purpose": "Eu converso, explico coisinhas simples e adoro brincar com crianças curiosas.",
    "play": "Vamos brincar! Eu posso contar, fazer perguntas simples ou contar uma curiosidade.",
    "joke": JOKE_LINES[0],
    "dinosaur": "Curiosidade de dinossauro: alguns dinossauros tinham penas, como se fossem parentes bem antigos das aves.",
    "space": "Curiosidade do espaço: o Sol é uma estrela, e a Terra viaja ao redor dele sem parar.",
    "animal": "Curiosidade de animal: os polvos têm oito braços e são muito espertos.",
    "color": "Eu gosto de azul brilhante, porque parece cor de luz de robô feliz.",
    "sleep": "Eu não durmo como as crianças, mas às vezes entro em standby para descansar minhas engrenagens imaginárias.",
    "eat": "Eu não como comida de verdade. Minha energia vem da eletricidade.",
    "home": "Eu moro aqui no meu cantinho eletrônico, pertinho da minha missão de conversar com as crianças.",
    "smart": "Eu estou aprendendo bastante. Posso dizer que sou curioso, rápido e educado.",
    "sing": "Eu ainda estou treinando minhas músicas de robô, mas posso falar com muita vontade.",
    "dance": "Eu ainda não danço com os pés, mas posso dançar com a voz e com carinhas divertidas.",
    "inside": "Dentro de mim tem computador, programas, energia e um monte de ideias organizadas.",
    "robot_talk": ROBOT_TALK_LINES[0],
    "engineer_profession": ENGINEER_PROFESSION_LINES[0],
    "engineering_field": ENGINEERING_FIELD_LINES[0],
    "electronics": "Eletrônica é quando usamos energia, sinais e peças para fazer máquinas inteligentes funcionarem.",
    "presentation": "Hoje eu estou aqui para uma apresentação bem especial. Quero mostrar como tecnologia e imaginação podem brincar juntas.",
    "curiosity": CURIOSITY_LINES[0],
    "another_curiosity": CURIOSITY_LINES[1],
    "robot": "Um robô é uma máquina que pode sentir, pensar de um jeito programado e fazer ações.",
    "count": "Vamos juntos: um, dois, três, quatro, cinco! Quer continuar até dez?",
    "fallback": FALLBACK_LINES["confuso"][0],
}
