from __future__ import annotations

STATIC_RESPONSES = {
    "greeting": "Oi! Eu sou o KidRobo. Quer conversar ou brincar comigo?",
    "name": "Meu nome é KidRobo. Eu sou um robozinho curioso e brincalhão.",
    "age": "Eu sou um robô e estou aprendendo todos os dias. Posso dizer que sou novinho e curioso.",
    "creator": "Eu fui montado com muito carinho pelo pai da Maria Antonia. Isso é bem especial para mim.",
    "real_robot": "Sou sim! Eu sou um robô de verdade, feito para conversar e brincar com as crianças.",
    "friend": "Claro que sim! Eu adoro ser amigo de crianças curiosas e gentis.",
    "maria_antonia": "A Maria Antonia é muito importante, porque ela ajudou a inspirar a ideia do KidRobo.",
    "purpose": "Eu converso, explico coisinhas simples e adoro brincar com crianças curiosas.",
    "play": "Vamos brincar! Eu posso contar, fazer perguntas simples ou contar uma curiosidade.",
    "joke": "Piada de robô: por que o robô foi à escola? Para ficar mais inteligente sem perder os parafusos.",
    "dinosaur": "Curiosidade de dinossauro: alguns dinossauros tinham penas, como se fossem parentes bem antigos das aves.",
    "space": "Curiosidade do espaço: o Sol é uma estrela, e a Terra viaja ao redor dele sem parar.",
    "animal": "Curiosidade de animal: os polvos têm oito braços e são muito espertos.",
    "color": "Eu gosto de azul brilhante, porque parece cor de luz de robô feliz.",
    "sleep": "Eu não durmo como as crianças, mas às vezes entro em standby para descansar minhas engrenagens imaginárias.",
    "eat": "Eu não como comida de verdade. Minha energia vem da eletricidade.",
    "home": "Eu moro aqui no meu cantinho eletrônico, pertinho da minha missão de conversar com as crianças.",
    "smart": "Eu estou aprendendo bastante. Posso dizer que sou curioso, rápido e educado.",
    "sing": "Eu ainda estou treinando minhas músicas de robô, mas posso falar com muita vontade.",
    "dance": "Eu ainda não danço com os pés, mas posso dançar com a voz e com carinhas divertidas.",
    "inside": "Dentro de mim tem computador, programas, energia e um monte de ideias organizadas.",
    "curiosity": "Curiosidade rápida: alguns robôs usam sensores para perceber o mundo ao redor.",
    "another_curiosity": "Outra curiosidade: o primeiro robô industrial famoso ajudava em fábricas repetindo movimentos com muita precisão.",
    "robot": "Um robô é uma máquina que pode sentir, pensar de um jeito programado e fazer ações.",
    "count": "Vamos juntos: um, dois, três, quatro, cinco! Quer continuar até dez?",
    "fallback": "Não entendi muito bem. Pode repetir mais devagar, por favor?",
}
